### ISSUE TITLE
Error opening file

### ISSUE THREAD

**Issue by xTCry** [Smertig/among-us-replayer#1]
All necessary files are present...

![image](https://user-images.githubusercontent.com/5994290/96830032-62547a80-1443-11eb-8ffe-6a89dacb97f0.png)

Could this be an error due to the screen resolution?

**Comment by Smertig** [comment]
Thank you for report!

8192x8192 is a maximum texture size defined by your graphics driver. However `skeld.png` texture is really big, so replayer can't load it as a single piece. I will fix this issue in the future release. 

For now you can use slightly modified resources ([res.zip](https://github.com/Smertig/among-us-replayer/files/5420651/res.zip)) with half-sized map texture.
