### ISSUE TITLE
New game assets

### ISSUE THREAD

**Issue by Johannes7k75** [Smertig/among-us-replayer#16]
Add the new Player, Body and Ghost assets so the newer replays can be displayed.
There was also a change of the game assets on version `2021.6.15`
Where the obvioused change is the rotation of the dead body

**Comment by milenakos** [comment]
i don't think this repository is active - last update to it was over a year ago
you can use [Sawa90's replay system](https://github.com/sawa90/AmongUsReplayInWindow) instead.

**Comment by Johannes7k75** [comment]
Yes but recently the amongus-replay-mod was recently updated
