### ISSUE TITLE
Need Build instruction

### ISSUE THREAD

**Issue by xTCry** [Smertig/among-us-replayer#2]
Можно инструкцию для сборки

Версию C++ и в каком редакторе это лучше открыть 

![image](https://user-images.githubusercontent.com/5994290/96894118-1120a700-1494-11eb-8a54-e911687ca638.png)

**Comment by Smertig** [comment]
Добавил инструкцию по сборке и требования в [README](https://github.com/Smertig/among-us-replayer#how-to-build). Также уменьшил требуемую версию C++ с 20-й до 17-й, ошибки со скриншота должны пропасть.

Для разработки можно использовать любой редактор, который поддерживает CMake-based проекты. Я предпочитаю CLion, однако VS и VS Code тоже должны подойти.

P.S. В будущем лучше использовать английский язык при создании Issue.
