### ISSUE TITLE
Hide/minimize player and file dialog windows

### ISSUE THREAD

**Issue by dluiscosta** [Smertig/among-us-replayer#9]
I've encountered this project recently and so far have not found a way to minimize (or completely hide) the two windows that overlay the replay, namelly the player and the file dialog tabs.

For me, they take a big portion of my screen and obstruct a considerable part of what is being reproduced (shown bellow).

Am I missing something? If not, I suggest that at least a minimize button is added to each of these windows. Either way, this is an UX issue.

![Screenshot 2020-12-01 035226](https://user-images.githubusercontent.com/9122632/100706972-ab73e480-3388-11eb-920a-d357140d58dc.png)

**Comment by Smertig** [comment]
Hi. Thanks for suggestion.
File dialog is already minimizable (#5), but I didn't publish new release yet. If you want to use it right now, grab latest debug version [here](https://github.com/Smertig/among-us-replayer/actions/runs/377578927).

As for player window, I'll make it minimizable too.

**Comment by dluiscosta** [comment]
@Smertig thanks for the reply. Feel free to close this issue either now or when both features are available.
